nelmio_api_doc:
    documentation:
        info:
            title: Calculator
            description: Xsolla test work
            version: 1.0.0
    areas:
        path_patterns:
            - ^(?!(\/api|\/_|\/doc|\/$))